In [1]:
import pandas as pd

In [3]:
df = pd.read_parquet('/Users/nojonghyeon/Documents/GitHub/ido/noh/019/train/part-000001.parquet')

In [4]:
df.head()

,source,split,content,messages,token_count
0,009.전문분야_기술과학_한국어 멀티세션 데이터,train,안녕하세요! 궁금한 것이 있는데 질문해도 될까요? 네 필요한 것이 있으시면 질문해주...,"[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",438
1,009.전문분야_기술과학_한국어 멀티세션 데이터,train,대화한지 세시간밖에 안됐는데 또 궁금한 점이 생겼어 네 지난번엔 이호길 박사에 대해...,"[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",350
2,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕? 지난 대화에서 4주나 흘렀네. 난 주말에 골프를 치며 보냈어. 안녕하세요, ...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",232
3,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕, 기억나니? 6주일 전에 미국의 기술자 아누셰흐 안사리에 대해 이야기했었지? ...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",262
4,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕, 오늘 날씨가 좋네! 너는 뭐하고 있었어? 안녕하세요, 항상 준비하고 있어요...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",261

In [5]:
df['content'].nunique()

4997

In [ ]:
df[df.duplicated(subset=['content'], keep=False)]

,source,split,content,messages,token_count
35,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕하세요, 저는 최근에 정보/통신 관련 강의를 듣고 있습니다. 궁금한 점이 생겨서...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",403
36,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕하세요, 여기가 컴퓨터 프로그래밍에 대해 잘 아는 AI도우미인가요? 네, 맞습니...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",315
37,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕하세요, 저는 최근에 정보/통신 관련 강의를 듣고 있습니다. 궁금한 점이 생겨서...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",403
38,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕하세요, 여기가 컴퓨터 프로그래밍에 대해 잘 아는 AI도우미인가요? 네, 맞습니...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",315
1080,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕하세요, 또 질문하러 왔습니다. 안녕하세요! 무엇이든 물어보세요. 저는 정보/통...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",318
1081,009.전문분야_기술과학_한국어 멀티세션 데이터,train,"안녕하세요, 또 질문하러 왔습니다. 안녕하세요! 무엇이든 물어보세요. 저는 정보/통...","[{'role': 'system', 'content': '당신은 기술과학 전문 비서...",318

In [7]:
df.drop_duplicates(subset=['content'], keep='first', inplace=True)

In [8]:
df['content'].nunique()

4997

In [9]:
len(df)

4997

In [10]:
df.to_parquet('../data/korean_processed/_staging/009/train/part-000001.parquet', index=False)

In [11]:
num = 1
root = '../data/korean_processed/_staging/novel24/val/part-'
while True:
    try:
        df = pd.read_parquet(f'{root}{num:06d}.parquet')
    except:
        print('file done')
        break
    ori_len = len(df)
    df.drop_duplicates(subset=['content'], keep='first', inplace=True)
    after_len = len(df)
    df.to_parquet(f'{root}{num:06d}.parquet', index=False)
    diff = ori_len - after_len
    if diff != 0:
        print(diff, num)
    num += 1

1 1
1 2
file done

In [2]:
print(f'{1:06d}')

000001